version: '3.8'

name: simple-file-sharing-environment

services:
# Postgres GUI
  postgres-gui:
    container_name: postgres-gui
    image: dpage/pgadmin4
    ports:
      # - "5050:80"
      - "5050:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_ENABLE_TLS: true
    volumes:
      # Enabling HTTPS
      - ./cert/localhost.cert:/certs/server.cert
      - ./cert/localhost.key:/certs/server.key
      # Load config file
      # - ./servers.json:/pgadmin4/servers.json
      - ./servers-ssl.json:/pgadmin4/servers.json
    depends_on:
      - postgres

# Database service definition
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
    ports:
      - "5432:5432"
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.cert
      -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
    #   - ./data/postgres:/var/lib/postgresql/data
      - ./cert/localhost.cert:/var/lib/postgresql/server.cert
      - ./cert/localhost.key:/var/lib/postgresql/server.key

# Minio service definition
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-password
    command: server /data --console-address ":9090" --certs-dir "/certs"
    volumes:
      # - ./data/minio:/data
      # Certs for console
      - ./cert/localhost.cert:/certs/public.crt
      - ./cert/localhost.key:/certs/private.key
      # Certs for MinIO client to access
      - ./cert/minio/public.crt:/certs/minio/public.crt
      - ./cert/minio/private.key:/certs/minio/private.key

# Create default bucket on Minio startup
  createbucket:
    container_name: create_bucket_task
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc --insecure alias set minio https://minio:9000 minio-admin minio-password;
      /usr/bin/mc --insecure mb minio/sfs-storage;
      /usr/bin/mc --insecure anonymous set public minio/sfs-storage;
      /usr/bin/mc --insecure admin user svcacct add \
      --access-key local-access-key                 \
      --secret-key local-secret-key                 \
      minio                                         \
      minio-admin;
      "