version: '3.8'

name: simple-file-storage-environment

networks:
  local:

services:
# Database service definition
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - local

# Minio service definition
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: local
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9090"
    networks:
      - local