version: '3.8'

services:
  postgres:
    user: root
    image: postgres:latest
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
    ports:
      - '5432:5432'
    networks:
      - local
networks:
  local: