version: '3.8'

services:
  postgres:
    user: root
    image: postgres:latest
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
      PGDATA: '/var/lib/pg_data'
    ports:
      - '8001:5432'
    networks:
      - local
    volumes:
      - './.data:/var/lib/postgresql/data'
networks:
  local: