version: '3.9'

name: simple-file-storage-stack
services:
  simple-file-storage:
    container_name: simple-file-storage
    build: .
    environment:
      DATABASE_URL: "postgres://local:password@postgres:5432/local"
      
      PORT: 8000
      ORIGIN: "http://host.docker.internal:5000"
      
      ACCESS_TOKEN_SECRET: ""
      REFRESH_TOKEN_SECRET: ""

      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_BUCKET_NAME: ""
      AWS_REGION: ""
      
      MINIO: true
      ENDPOINT: "http://minio:9000"
    ports:
      - 8000:8000
    depends_on:
      - minio
      - postgres
    networks:
      - local
  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: local
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9090"
    networks:
      local:
        aliases:
          - minio
  postgres:
    container_name: postgres
    user: root
    image: postgres:latest
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      local: 
        aliases:
          - postgres
networks:
  local:
